name: "Terraform Plan"

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'sample_VM'

steps:

# - task: TerraformInstaller@0
#   displayName: "Install Terraform"
#   inputs:
#     terraformVersion: '1.3.9'
#     terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'

# - script: |
#     terraform init
#     terraform plan -out=terraform.tfplan
#   displayName: 'Terraform Plan'
- task: PowerShell@2
  displayName: 'Validate PowerShell Scripts'
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Packaging PowerShell scripts for drop"
      if (Test-Path '$(Build.SourcesDirectory)') {
        Write-Output "PowerShell scripts directory found!"
      } else {
        Write-Error "PowerShell scripts directory not found!"
      }

# Publish Artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish PowerShellScripts Artifact'
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'PowerShellScripts'