# Build number format: TerraformPlan_YYYYMMDD.Revision
name: TerraformPlan_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main

pool: 
  name: Azure Pipelines 
  
steps:

# Example Terraform steps (commented out)
# - task: TerraformInstaller@0
#   displayName: "Install Terraform"
#   inputs:
#     terraformVersion: '1.3.9'
#     terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'

# - script: |
#     terraform init
#     terraform plan -out=terraform.tfplan
#   displayName: 'Terraform Plan'

- task: PowerShell@2
  displayName: 'Validate PowerShell Scripts'
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Packaging PowerShell scripts for drop"
      if (Test-Path '$(Build.SourcesDirectory)') {
        Write-Output "PowerShell scripts directory found!"
      } else {
        Write-Error "PowerShell scripts directory not found!"
      }

# Publish Artifact with versioning
- task: PublishPipelineArtifact@1
  displayName: 'Publish PowerShellScripts Artifact'
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifactName: 'PowerShellScripts_$(Build.BuildNumber)'
